//! GitHub integration.
//!
//! sluss publishes every gate outcome as a check run bound to the head
//! commit — summary, rationale and line annotations live there, and branch
//! protection turns the check into an actual merge gate. An
//! approve/request-changes/comment review is submitted alongside, but the
//! check run is the record.
//!
//! Two auth modes: a personal token (snapshot + reviews only — GitHub
//! restricts check-run writes to Apps) or GitHub App credentials, which
//! make the gate real. In App mode every call is scoped to the repo's
//! installation, with installation ids cached per repo.

mod publish;
mod snapshot;

pub use publish::PublishReceipt;

use std::collections::HashMap;
use std::sync::Mutex;

use anyhow::{Context, Result, bail};
use octocrab::Octocrab;
use octocrab::models::{AppId, InstallationId};
use sluss_core::ChangeRef;

/// The check-run name sluss reports under (and excludes from its own view
/// of CI, so a previous sluss verdict never counts as "CI").
pub const DEFAULT_CHECK_NAME: &str = "sluss";

enum Auth {
    /// Personal token — client is usable as-is.
    Direct,
    /// JWT-authed as the App — every call must be scoped to a repo's
    /// installation first.
    App,
}

pub struct GitHubForge {
    client: Octocrab,
    auth: Auth,
    check_name: String,
    /// repo -> installation id, learned on first contact.
    installations: Mutex<HashMap<String, InstallationId>>,
}

impl GitHubForge {
    fn with_auth(client: Octocrab, auth: Auth) -> Self {
        Self {
            client,
            auth,
            check_name: DEFAULT_CHECK_NAME.into(),
            installations: Mutex::new(HashMap::new()),
        }
    }

    pub fn new(client: Octocrab) -> Self {
        Self::with_auth(client, Auth::Direct)
    }

    /// Personal-token auth: covers snapshot and reviews, but GitHub rejects
    /// check-run creation — the merge gate needs [`GitHubForge::from_app`].
    pub fn from_token(token: impl Into<String>) -> Result<Self> {
        let client = Octocrab::builder()
            .personal_token(token.into())
            .build()
            .context("building octocrab client")?;
        Ok(Self::new(client))
    }

    /// GitHub App auth: the full feature set, including check runs. Takes
    /// the App id and the RSA private key PEM as generated by GitHub's
    /// "Generate a private key" button.
    pub fn from_app(app_id: u64, private_key_pem: &[u8]) -> Result<Self> {
        let key = jsonwebtoken::EncodingKey::from_rsa_pem(private_key_pem)
            .context("app private key is not valid RSA PEM")?;
        let client = Octocrab::builder()
            .app(AppId(app_id), key)
            .build()
            .context("building app-authed octocrab client")?;
        Ok(Self::with_auth(client, Auth::App))
    }

    pub fn with_check_name(mut self, name: impl Into<String>) -> Self {
        self.check_name = name.into();
        self
    }

    /// True when check-run creation (the real gate) is available.
    pub fn can_gate(&self) -> bool {
        matches!(self.auth, Auth::App)
    }

    pub(crate) fn check_name(&self) -> &str {
        &self.check_name
    }

    /// A client authorized to act on `owner/repo`: the client itself in
    /// token mode, an installation-scoped client in App mode.
    pub(crate) async fn client_for(&self, owner: &str, repo: &str) -> Result<Octocrab> {
        match self.auth {
            Auth::Direct => Ok(self.client.clone()),
            Auth::App => {
                let key = format!("{owner}/{repo}");
                let cached = self.installations.lock().expect("poisoned").get(&key).copied();
                let id = match cached {
                    Some(id) => id,
                    None => {
                        let installation = self
                            .client
                            .apps()
                            .get_repository_installation(owner, repo)
                            .await
                            .with_context(|| format!("app is not installed on {key}"))?;
                        self.installations
                            .lock()
                            .expect("poisoned")
                            .insert(key, installation.id);
                        installation.id
                    }
                };
                self.client
                    .installation(id)
                    .context("scoping client to installation")
            }
        }
    }

    /// Split `owner/repo` out of a change ref, refusing GitLab refs.
    pub(crate) fn owner_repo<'a>(&self, change: &'a ChangeRef) -> Result<(&'a str, &'a str)> {
        if change.forge != sluss_core::Forge::GitHub {
            bail!("GitHubForge got a {:?} change", change.forge);
        }
        change
            .repo
            .split_once('/')
            .with_context(|| format!("repo '{}' is not owner/repo", change.repo))
    }
}
